#type: node
#context: dop
#internal: dragproperties
#icon: DOP/dragproperties

= Soft Body Collision Properties =

"""Holds drag coefficients for a DOP object."""

Stores the drag coefficients for a DOP object (e.g, cloth).

    The drag parameters express how fast the cloth will adapt its velocity to the velocity of the surrounding air, such as wind.

    Tangent Drag:
        #channels: /tangentdrag
        
        The component of drag in the directions tangent to the cloth surface. Increasing this will make the cloth go along with any wind that blows tangent to the surface.

    Normal Drag:
        #channels: /normaldrag
        
        The direction normal to the cloth polygons. Increasing this will make the cloth go along with any wind that blows against it. For realistic cloth-wind interaction, the Normal Drag should be chosen larger (about 10 times larger) than the tangent drag.

        TIP:
            An easy way to set a wind speed is by using the __External Velocity Offset__.

    External Velocity Field:
        #channels: /externalvelocityfield

        The name of the external velocity fields on affectors that the cloth will respond to. If this parameter is chosen to be `vel`, then the cloth reacts to fluids and smoke when the __Tangent Drag__ and the __Normal Drag__ are chosen sufficiently large. The __Tangent Drag__ and __Normal Drag__ forces are computed by comparing the cloth's velocity with the external velocity.

    External Velocity Offset:
        #channels: /externalvelocityoffset

        This offset is added to any velocity that's read from the velocity field. When there's no velocity field, then the offset can be used to create a wind force which has constant velocity everywhere. This wind effect is more realistic and more accurate than the wind that is generated by DOP Forces.


@inputs
    [Include:standard_data_inputs]

@outputs
    [Include:standard_data_outputs]

@locals
    [Include:standard_data_locals]

    [Include:standard_locals]


@related
    - [Node:dop/wireobject]
    - [Node:dop/wireconfigureobject]
    - [Node:dop/clothobject]
    - [Node:dop/clothconfigureobject]

